# BOOKING SERVICE - Profil DEV

# Spring
spring:
  # Database
  datasource:
    url: jdbc:mysql://localhost:3306/booking_db_dev?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:

# Booking
booking:
  max-days-advance: 30
  cancellation-hours: 0

# Logging
logging:
  level:
    com.restobook.bookingservice: DEBUG
