# RESTAURANT SERVICE - Profil PROD

# Spring
spring:
  # Database
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME:restaurant_db}?useSSL=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# Logging
logging:
  level:
    com.restobook.restaurantservice: INFO
