# EUREKA SERVICE

# Spring Configuration
spring:
  # Application Name
  application:
    name: eureka-service

  # Environment Variables Configuration
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8085}

  # Eureka Configuration
  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 2000
        max-interval: 10000
        multiplier: 2
        max-attempts: 5

  # Profile Configuration
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:}
